Airport.create(code: 'JFK-New York City')
Airport.create(code: 'POP-PuertaPlata,DR')
Airport.create(code: 'MDE-Medellin,Columbia')
Airport.create(code: 'GIG-Rio de janiero')
Airport.create(code: 'CRK-Angeles City,Phillipines')
